/*PESSOA*/
CREATE TABLE PESSOA(
NOME VARCHAR2(200 BYTE) NOT NULL,
IDADE NUMBER NOT NULL,
SEXO VARCHAR2(2 BYTE) NOT NULL,
CPF VARCHAR(11 BYTE) NOT NULL,
ID_ENDERECO NUMBER,
NUMERO_CONTA NUMBER,
CONSTRAINT PESSOA_PK PRIMARY KEY(CPF) ENABLE,
CONSTRAINT CONTA_FK FOREIGN KEY(NUMERO_CONTA) REFERENCES CONTA(NUMERO) ENABLE,
CONSTRAINT ENDERECO_FK FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO) ENABLE
);
